kpt_shape:
- 2
- 3
names:
  0: Weld
  1: Stud
path: /home/ubuntu/algo-ai-training/data/test_merge_dataset/sample_small_keypoint_dataset/input/Dataloop/keypoint/2025-11-20_13-48-14/raw_data_3764/split_data
test: test/images
train: train/images
val: validation/images
