kpt_shape:
- 2
- 3
names:
  0: Weld
  1: Stud
  2: MigWeld
  3: BackSideWeldNut
  4: Porosity
  5: SeamGood
  6: SeamBad
  7: WeldNut
  8: Rivnut
  9: Drill
  10: SPR
  11: Hole
  12: Unknown
path: /home/ubuntu/algo-ai-training/data/test_27072025/processed
test: test/images
train: train/images
val: validation/images
